version: '3'
services:
  backend-challenge:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    container_name: backend-challenge

    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
